//
// Created by Andrew Bailey on 10/14/19.
//

#ifndef EVENTDETECTION_SRC_EVENTDETECTION_HPP_
#define EVENTDETECTION_SRC_EVENTDETECTION_HPP_


class EventDetection {

};

#endif //EVENTDETECTION_SRC_EVENTDETECTION_HPP_
